# Generated by Django 4.1.7 on 2023-02-27 17:58

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='videos/')),
                ('poster_image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='posters/')),
            ],
        ),
    ]
